/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.esic.beta;


import fr.esic.model.Propreties;
import fr.esic.connected.Requete;
import fr.esic.model.User;
import java.sql.Date;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.text.html.HTMLEditorKit;


/**
 *
 * @author Huawei
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
       jTabbedPane3.setEnabledAt(2, false);
        jldatenom.setText("Dernier Connexion : "+Propreties.USER_CONNECT.getDate());
        jlobjective.setText("Objective Hebdomadaire : "+Propreties.USER_CONNECT.getContenu());
        jljournalier.setText("Objective Journalier : "+Propreties.USER_CONNECT.getJournalier());
         jlmail.setText("Votre Mail : "+Propreties.USER_CONNECT.getMail());
        jlnom.setText("Votre nom :"+Propreties.USER_CONNECT.getNom());
        jlprenom.setText("Votre Prenom : "+Propreties.USER_CONNECT.getPrenom());
        jlsexe.setText("Votre Sexe :"+Propreties.USER_CONNECT.getSexe());
        jlmdp.setText("Votre Password :" +Propreties.USER_CONNECT.getMdp());
        jlpoid.setText("Votre Poids : "+Propreties.USER_CONNECT.getPoids());
        jltaille.setText("Votre Taille : "+Propreties.USER_CONNECT.getTaille());
        jlage.setText("Votre Age : "+Propreties.USER_CONNECT.getAge());
        
        
      

             

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jldatenom = new javax.swing.JLabel();
        jlobjective = new javax.swing.JLabel();
        btndeconnexion = new javax.swing.JButton();
        jljournalier = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtobjective = new javax.swing.JTextArea();
        btnajoute = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtjournalier = new javax.swing.JTextArea();
        btnjournalier = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtsexe = new javax.swing.JTextField();
        txtmdp = new javax.swing.JTextField();
        txtpoids = new javax.swing.JTextField();
        txttaille = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        btnedits = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jlnom = new javax.swing.JLabel();
        jlprenom = new javax.swing.JLabel();
        jltaille = new javax.swing.JLabel();
        jlpoid = new javax.swing.JLabel();
        jlmdp = new javax.swing.JLabel();
        jlsexe = new javax.swing.JLabel();
        jlage = new javax.swing.JLabel();
        jlmail = new javax.swing.JLabel();
        jphelp = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txthelp = new javax.swing.JTextArea();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jldatenom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jldatenom.setForeground(new java.awt.Color(0, 0, 0));
        jldatenom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlobjective.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlobjective.setForeground(new java.awt.Color(0, 0, 0));

        btndeconnexion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btndeconnexion.setText("DECONNEXION");
        btndeconnexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeconnexionActionPerformed(evt);
            }
        });

        jljournalier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jljournalier.setForeground(new java.awt.Color(0, 0, 0));

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Logo_objective-01-1.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jljournalier, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                            .addComponent(jlobjective, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jldatenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btndeconnexion))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel12)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jldatenom, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlobjective, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jljournalier, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addComponent(btndeconnexion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Objective Hebdomadaire ");

        txtobjective.setColumns(20);
        txtobjective.setRows(5);
        jScrollPane1.setViewportView(txtobjective);

        btnajoute.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnajoute.setText("AJOUTE");
        btnajoute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnajouteActionPerformed(evt);
            }
        });

        jLabel10.setBackground(new java.awt.Color(0, 0, 153));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("X");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Objective Journalier ");

        txtjournalier.setColumns(20);
        txtjournalier.setRows(5);
        jScrollPane2.setViewportView(txtjournalier);

        btnjournalier.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnjournalier.setText("AJOUTE");
        btnjournalier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnjournalierActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(47, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnjournalier, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnajoute, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnajoute, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnjournalier, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Objective", jPanel1);

        jPanel6.setBackground(new java.awt.Color(0, 102, 153));
        jPanel6.setForeground(new java.awt.Color(0, 102, 153));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("NOM");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("PRENOM");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("SEXE");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("PASSWORD");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("POIDS");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("TAILLE");

        txtnom.setBackground(new java.awt.Color(255, 255, 255));
        txtnom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtnom.setForeground(new java.awt.Color(0, 0, 0));

        txtprenom.setBackground(new java.awt.Color(255, 255, 255));
        txtprenom.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtprenom.setForeground(new java.awt.Color(0, 0, 0));
        txtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomActionPerformed(evt);
            }
        });

        txtsexe.setBackground(new java.awt.Color(255, 255, 255));
        txtsexe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtsexe.setForeground(new java.awt.Color(0, 0, 0));
        txtsexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsexeActionPerformed(evt);
            }
        });

        txtmdp.setBackground(new java.awt.Color(255, 255, 255));
        txtmdp.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtmdp.setForeground(new java.awt.Color(0, 0, 0));

        txtpoids.setBackground(new java.awt.Color(255, 255, 255));
        txtpoids.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtpoids.setForeground(new java.awt.Color(0, 0, 0));

        txttaille.setBackground(new java.awt.Color(255, 255, 255));
        txttaille.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txttaille.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("AGE");

        txtage.setBackground(new java.awt.Color(255, 255, 255));
        txtage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtage.setForeground(new java.awt.Color(0, 0, 0));

        btnedits.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnedits.setText("MODIFIER");
        btnedits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneditsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addGap(42, 42, 42)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnom, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(txtprenom)
                    .addComponent(txtsexe)
                    .addComponent(txtmdp)
                    .addComponent(txtpoids)
                    .addComponent(txttaille)
                    .addComponent(txtage))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnedits, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(16, 16, 16)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtmdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtpoids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txttaille, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnedits, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/3289566-assistant-educator-professor-showing-teacher-teaching_107089.png"))); // NOI18N

        jlnom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlnom.setForeground(new java.awt.Color(0, 0, 0));

        jlprenom.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlprenom.setForeground(new java.awt.Color(0, 0, 0));

        jltaille.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jltaille.setForeground(new java.awt.Color(0, 0, 0));

        jlpoid.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlpoid.setForeground(new java.awt.Color(0, 0, 0));

        jlmdp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlmdp.setForeground(new java.awt.Color(0, 0, 0));

        jlsexe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlsexe.setForeground(new java.awt.Color(0, 0, 0));

        jlage.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlage.setForeground(new java.awt.Color(0, 0, 0));

        jlmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jlmail.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlage, javax.swing.GroupLayout.DEFAULT_SIZE, 172, Short.MAX_VALUE)
                        .addComponent(jltaille, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlpoid, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlmdp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlsexe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlnom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlprenom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jlmail, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jlmail, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlnom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlprenom, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlsexe, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlmdp, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlpoid, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jltaille, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlage, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane3.addTab("Profile", jPanel4);

        jPanel8.setBackground(new java.awt.Color(0, 102, 204));

        txthelp.setBackground(new java.awt.Color(255, 255, 255));
        txthelp.setColumns(20);
        txthelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txthelp.setForeground(new java.awt.Color(0, 0, 0));
        txthelp.setRows(5);
        jScrollPane3.setViewportView(txthelp);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 658, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jphelpLayout = new javax.swing.GroupLayout(jphelp);
        jphelp.setLayout(jphelpLayout);
        jphelpLayout.setHorizontalGroup(
            jphelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jphelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jphelpLayout.setVerticalGroup(
            jphelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jphelpLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane3.addTab("Help", jphelp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jTabbedPane3.getAccessibleContext().setAccessibleName("Objective");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndeconnexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeconnexionActionPerformed
       Connexion cn = new Connexion();
       cn.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_btndeconnexionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     try {
                     String nomhelp = Propreties.USER_CONNECT.getNom();
            String prenomhelp = Propreties.USER_CONNECT.getPrenom();
            txthelp.setText("Bonjour, cher utilisateur "+nomhelp+" "+prenomhelp+"\n" +
"notre société a pour objectif de sensibiliser les gens sur divers sujets\n" +
"cette application a été faite pour vous faciliter le suivi de votre santé afin de prévenir l'obésité.\n" +
"dans cette application, vous trouverez\n" +
"-comment se motiver en ajoutant des objectifs hebdomadaires et jounaliers\n" +
"-vous informer de vos progrès\n" +
"-vous aider à progresser pour atteindre vos objectifs\n" +
"-vous donne un aperçu de vos informations, que vous pouvez modifier\n" +
"merci d'utiliser notre application, bon courage");
            txthelp.setEditable(false);
            
            String nom = Propreties.USER_CONNECT.getNom();
            String prenom = Propreties.USER_CONNECT.getPrenom();
            String sexe = Propreties.USER_CONNECT.getSexe();
            String journalier = Propreties.USER_CONNECT.getJournalier();
            String contenu = Propreties.USER_CONNECT.getContenu();
            String poids = Propreties.USER_CONNECT.getPoids();
            String taille = Propreties.USER_CONNECT.getTaille();
            Date date1 = Propreties.USER_CONNECT.getDate();
            if (contenu == null) {
               jlobjective.setVisible(false);
                
            }
            if (journalier == null) {
               jljournalier.setVisible(false);
                
            }
            
            
               
            if (date1 ==null) {
              jTabbedPane3.setEnabledAt(2, true);
               jTabbedPane3.setSelectedIndex(2);
               jldatenom.setVisible(false);
                
            }
             if (sexe ==null) {
              JOptionPane.showMessageDialog(rootPane, "Veuillez remplir  votre sexe");
                
            }
            if (poids ==null) {
              JOptionPane.showMessageDialog(rootPane, "Veuillez remplir  votre Poids");
                
            }
            if (taille ==null) {
              JOptionPane.showMessageDialog(rootPane, "Veuillez remplir  votre Taille");
                
            }
               
         
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "exception"+e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void btnajouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnajouteActionPerformed
        String contenu = txtobjective.getText();
        String log = Propreties.USER_CONNECT.getMail();
        try {
            Requete.insertObjective(contenu, log);
            JOptionPane.showMessageDialog(rootPane, "Votre Objective a été enregistré");
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "exception"+e.getMessage());
        }
    }//GEN-LAST:event_btnajouteActionPerformed

    private void btneditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneditsActionPerformed
       String Bdnom = Propreties.USER_CONNECT.getNom();
       String Bdprenom = Propreties.USER_CONNECT.getPrenom();
       String Bdsexe = Propreties.USER_CONNECT.getSexe();
       String Bdmdp = Propreties.USER_CONNECT.getMdp();
       String Bdpoids = Propreties.USER_CONNECT.getPoids();
       String Bdtaille = Propreties.USER_CONNECT.getTaille();
       String Bdage = Propreties.USER_CONNECT.getAge();
       String nom = txtnom.getText();
       String prenom = txtprenom.getText();
       String sexe = txtsexe.getText();
       String mdp = txtmdp.getText();
       String poids = txtpoids.getText();
       String taille = txttaille.getText();
       String age = txtage.getText();
       String log = Propreties.USER_CONNECT.getMail();
               try {
                    if (nom.isEmpty() && prenom.isEmpty() && sexe.isEmpty() && mdp.isEmpty() && poids.isEmpty() && taille.isEmpty() ) {
            Requete.updateProfile(Bdnom, Bdprenom, Bdsexe, Bdmdp, Bdpoids, Bdtaille, age, log);
            JOptionPane.showMessageDialog(rootPane, "votre age a été modifié");
        }else if (nom.isEmpty() && prenom.isEmpty() && sexe.isEmpty() && mdp.isEmpty() && poids.isEmpty() && age.isEmpty() ) {
            Requete.updateProfile(Bdnom, Bdprenom, Bdsexe, Bdmdp, Bdpoids, taille, Bdage, log);
            JOptionPane.showMessageDialog(rootPane, "votre taille a été modifié");
        }else if (nom.isEmpty() && prenom.isEmpty() && sexe.isEmpty() && mdp.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
            Requete.updateProfile(Bdnom, Bdprenom, Bdsexe, Bdmdp, poids, Bdtaille, Bdage, log);
            JOptionPane.showMessageDialog(rootPane, "votre poids a été modifié");
        }else if (nom.isEmpty() && prenom.isEmpty() && sexe.isEmpty() && poids.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
            Requete.updateProfile(Bdnom, Bdprenom, Bdsexe, mdp, Bdpoids, Bdtaille, Bdage, log);
            JOptionPane.showMessageDialog(rootPane, "votre password a été modifié");
        }else if (nom.isEmpty() && prenom.isEmpty() && mdp.isEmpty() && poids.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
            Requete.updateProfile(Bdnom, Bdprenom, sexe, Bdmdp, Bdpoids, Bdtaille, Bdage, log);
            JOptionPane.showMessageDialog(rootPane, "votre sexe a été modifié");
        }else if (nom.isEmpty() && sexe.isEmpty() && mdp.isEmpty() && poids.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
            Requete.updateProfile(Bdnom, prenom, Bdsexe, Bdmdp, Bdpoids, Bdtaille, Bdage, log);
            JOptionPane.showMessageDialog(rootPane, "votre prenom a été modifié");
        }else if (prenom.isEmpty() && sexe.isEmpty() && mdp.isEmpty() && poids.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
            Requete.updateProfile(nom, Bdprenom, Bdsexe, Bdmdp, Bdpoids, Bdtaille, Bdage, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
        }else if ( sexe.isEmpty() && mdp.isEmpty() && poids.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
            Requete.updateProfile(nom, prenom, Bdsexe, Bdmdp, Bdpoids, Bdtaille, Bdage, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
        }else if ( nom.isEmpty() && prenom.isEmpty() && poids.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
            Requete.updateProfile(Bdnom, Bdprenom, sexe, mdp, Bdpoids, Bdtaille, Bdage, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
        }else if ( nom.isEmpty() && prenom.isEmpty() && sexe.isEmpty() && mdp.isEmpty() && age.isEmpty() ) {
            Requete.updateProfile(Bdnom, Bdprenom, Bdsexe, Bdmdp, poids, taille, Bdage, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
        }else if ( nom.isEmpty() && prenom.isEmpty() && sexe.isEmpty() && mdp.isEmpty() && poids.isEmpty() ) {
            Requete.updateProfile(Bdnom, Bdprenom, Bdsexe, Bdmdp, Bdpoids, taille, age, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
        }else if ( nom.isEmpty() && prenom.isEmpty() && sexe.isEmpty()  ) {
            Requete.updateProfile(Bdnom, Bdprenom, Bdsexe, mdp, poids, taille, age, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
        }else if ( nom.isEmpty() && prenom.isEmpty() && mdp.isEmpty()  ) {
            Requete.updateProfile(Bdnom, Bdprenom, sexe, Bdmdp, poids, taille, age, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
         }else if ( mdp.isEmpty() && poids.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
            Requete.updateProfile(nom, prenom, sexe, Bdmdp, Bdpoids, Bdtaille, Bdage, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
         }else if ( nom.isEmpty() && prenom.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
            Requete.updateProfile(Bdnom, Bdprenom, sexe, mdp, poids, Bdtaille, Bdage, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
          }else if ( nom.isEmpty() && prenom.isEmpty() ) {
            Requete.updateProfile(Bdnom, Bdprenom, sexe, mdp, poids, taille, age, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
           }else if ( sexe.isEmpty() && mdp.isEmpty() ) {
            Requete.updateProfile(nom, prenom, Bdsexe, Bdmdp, poids, taille, age, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
            }else {
            Requete.updateProfile(nom, prenom, sexe, mdp, poids, taille, age, log);
            JOptionPane.showMessageDialog(rootPane, "votre profile a été modifié");
      }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, "exception"+e.getMessage());
        }
    }//GEN-LAST:event_btneditsActionPerformed

    private void txtsexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsexeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsexeActionPerformed

    private void txtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomActionPerformed

    private void btnjournalierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnjournalierActionPerformed
        // TODO add your handling code here:
        String journalier = txtjournalier.getText();
        String log = Propreties.USER_CONNECT.getMail();
        
        try {
            Requete.insertJournalier(journalier, log);
            JOptionPane.showMessageDialog(rootPane, "Votre Objective journalier a été enregistré");
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnjournalierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnajoute;
    private javax.swing.JButton btndeconnexion;
    private javax.swing.JButton btnedits;
    private javax.swing.JButton btnjournalier;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel jlage;
    private javax.swing.JLabel jldatenom;
    private javax.swing.JLabel jljournalier;
    private javax.swing.JLabel jlmail;
    private javax.swing.JLabel jlmdp;
    private javax.swing.JLabel jlnom;
    private javax.swing.JLabel jlobjective;
    private javax.swing.JLabel jlpoid;
    private javax.swing.JLabel jlprenom;
    private javax.swing.JLabel jlsexe;
    private javax.swing.JLabel jltaille;
    private javax.swing.JPanel jphelp;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextArea txthelp;
    private javax.swing.JTextArea txtjournalier;
    private javax.swing.JTextField txtmdp;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextArea txtobjective;
    private javax.swing.JTextField txtpoids;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtsexe;
    private javax.swing.JTextField txttaille;
    // End of variables declaration//GEN-END:variables
}
