/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fr.esic.beta;


import fr.esic.connected.Requete;
import fr.esic.model.User;
import javax.swing.JOptionPane;
/**
 *
 * @author Huawei
 */
public class Inscription extends javax.swing.JFrame {

    /**
     * Creates new form Inscription
     */
    public Inscription() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        txtprenom = new javax.swing.JTextField();
        txtsexe = new javax.swing.JTextField();
        txtmail = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtpoids = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttaiile = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btninscription = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PRENOM");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("SEXE");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("EMAIL");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("PASSWORD");

        txtnom.setBackground(new java.awt.Color(204, 204, 204));
        txtnom.setForeground(new java.awt.Color(0, 0, 0));

        txtprenom.setBackground(new java.awt.Color(204, 204, 204));

        txtsexe.setBackground(new java.awt.Color(204, 204, 204));
        txtsexe.setForeground(new java.awt.Color(0, 0, 0));

        txtmail.setBackground(new java.awt.Color(204, 204, 204));
        txtmail.setForeground(new java.awt.Color(0, 0, 0));

        txtpassword.setBackground(new java.awt.Color(204, 204, 204));
        txtpassword.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("POIDS");

        txtpoids.setBackground(new java.awt.Color(204, 204, 204));
        txtpoids.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("TAIILLE");

        txttaiile.setBackground(new java.awt.Color(204, 204, 204));
        txttaiile.setForeground(new java.awt.Color(0, 0, 0));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("AGE");

        txtage.setBackground(new java.awt.Color(204, 204, 204));
        txtage.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtage.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtprenom, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtnom, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txttaiile, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtmail, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(txtsexe)
                    .addComponent(txtpassword)
                    .addComponent(txtpoids)
                    .addComponent(txtage))
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtsexe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtpoids, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txttaiile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        btninscription.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btninscription.setText("S'inscrire");
        btninscription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btninscriptionActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/commentsinscrire-enligne.png"))); // NOI18N

        jLabel9.setBackground(new java.awt.Color(0, 0, 153));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(btninscription, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btninscription, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btninscriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btninscriptionActionPerformed
       String nom = txtnom.getText();
       String prenom = txtprenom.getText();
       String sexe = txtsexe.getText();
       String mail= txtmail.getText();
       String mdp = txtpassword.getText();
       String poids = txtpoids.getText();
       String taille = txttaiile.getText();
       String age = txtage.getText();
        try {
             if (mail.isEmpty() || mdp.isEmpty()) {
              JOptionPane.showConfirmDialog(rootPane, "Veuillez rentre  votre mail et Password");
            }else{
            if (sexe.isEmpty() && poids.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, null, mail, mdp, null, null, null)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
           }else if (sexe.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, null, mail, mdp, poids, null, null)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
             }else if (poids.isEmpty() && taille.isEmpty() && age.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, sexe, mail, mdp, null, null, null)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
             }else if (sexe.isEmpty() && poids.isEmpty() && taille.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, null, mail, mdp, null, null, age)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
            } else{
                if (sexe.isEmpty() && poids.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, null, mail, mdp, null, taille, age)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
            } else{
                if (age.isEmpty() && poids.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, sexe, mail, mdp, null, taille, null)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
            } else{
                if (sexe.isEmpty() && age.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, null, mail, mdp, poids, taille, null)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
            }
                
            else{
                    if (taille.isEmpty() && poids.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, sexe, mail, mdp, null, null, age)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
            }
            else{
                    if (taille.isEmpty() && age.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, sexe, mail, mdp, poids, null, null)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
            }
                    else{
                if (sexe.isEmpty() && taille.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, null, mail, mdp, poids, null, age)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
            } else{
                if (sexe.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, null, mail, mdp, poids, taille, age)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
            }else{
                if (poids.isEmpty() ) {
               Requete.insertPerson(new User(nom, prenom, sexe, mail, mdp, null, taille, age)); 
              JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
            
                }else{
               if (taille.isEmpty() ) {
             Requete.insertPerson(new User(nom, prenom, sexe, mail, mdp, poids, null, age)); 
            JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
                } else{
            Requete.insertPerson(new User(nom, prenom, sexe, mail, mdp, poids, taille, age));
            JOptionPane.showConfirmDialog(rootPane, "Inscription Complete");
            Connexion cn = new Connexion();
            cn.setVisible(true);
            this.setVisible(false);
            }
                }
            }
                }
                }
                    }
                }
                }
                }
            }
             }

            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "exception"+e.getMessage());
        }
        
    }//GEN-LAST:event_btninscriptionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btninscription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtmail;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtpoids;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtsexe;
    private javax.swing.JTextField txttaiile;
    // End of variables declaration//GEN-END:variables
}
